const config = {
    PROJECT_ID: process.env.NEXT_PUBLIC_PROJECT_ID,
    API_KEY: process.env.NEXT_PUBLIC_API_KEY,
    DATABASE_ID: process.env.NEXT_PUBLIC_DATABASE_ID,
    PATIENTS_COLLECTION_ID: process.env.NEXT_PUBLIC_PATIENTS_COLLECTION_ID,
    DOCTOR_COLLECTION_ID: process.env.NEXT_PUBLIC_DOCTOR_COLLECTION_ID,
    APPOINTMENT_COLLECTION_ID: process.env.NEXT_PUBLIC_APPOINTMENT_COLLECTION_ID,
    BUCKET_ID: process.env.NEXT_PUBLIC_BUCKET_ID,
    ENDPOINT: process.env.NEXT_PUBLIC_ENDPOINT,
};

export default config;